// +build !ignore_autogenerated

package target1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	peer1 "k8s.io/gengo/examples/conversion-gen/output_tests/peer1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*peer1.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_target1_Foo_To_peer1_Foo(a.(*Foo), b.(*peer1.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*peer1.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_peer1_Foo_To_target1_Foo(a.(*peer1.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubFooStruct)(nil), (*peer1.SubFooStruct)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_target1_SubFooStruct_To_peer1_SubFooStruct(a.(*SubFooStruct), b.(*peer1.SubFooStruct), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*peer1.SubFooStruct)(nil), (*SubFooStruct)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_peer1_SubFooStruct_To_target1_SubFooStruct(a.(*peer1.SubFooStruct), b.(*SubFooStruct), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_target1_Foo_To_peer1_Foo(in *Foo, out *peer1.Foo, s conversion.Scope) error {
	out.Str = in.Str
	out.Int64Ptr = (*int64)(unsafe.Pointer(in.Int64Ptr))
	if err := Convert_target1_SubFooStruct_To_peer1_SubFooStruct(&in.SubStruct, &out.SubStruct, s); err != nil {
		return err
	}
	return nil
}

// Convert_target1_Foo_To_peer1_Foo is an autogenerated conversion function.
func Convert_target1_Foo_To_peer1_Foo(in *Foo, out *peer1.Foo, s conversion.Scope) error {
	return autoConvert_target1_Foo_To_peer1_Foo(in, out, s)
}

func autoConvert_peer1_Foo_To_target1_Foo(in *peer1.Foo, out *Foo, s conversion.Scope) error {
	out.Str = in.Str
	out.Int64Ptr = (*int64)(unsafe.Pointer(in.Int64Ptr))
	if err := Convert_peer1_SubFooStruct_To_target1_SubFooStruct(&in.SubStruct, &out.SubStruct, s); err != nil {
		return err
	}
	return nil
}

// Convert_peer1_Foo_To_target1_Foo is an autogenerated conversion function.
func Convert_peer1_Foo_To_target1_Foo(in *peer1.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_peer1_Foo_To_target1_Foo(in, out, s)
}

func autoConvert_target1_SubFooStruct_To_peer1_SubFooStruct(in *SubFooStruct, out *peer1.SubFooStruct, s conversion.Scope) error {
	out.BoolSlice = *(*[]bool)(unsafe.Pointer(&in.BoolSlice))
	return nil
}

// Convert_target1_SubFooStruct_To_peer1_SubFooStruct is an autogenerated conversion function.
func Convert_target1_SubFooStruct_To_peer1_SubFooStruct(in *SubFooStruct, out *peer1.SubFooStruct, s conversion.Scope) error {
	return autoConvert_target1_SubFooStruct_To_peer1_SubFooStruct(in, out, s)
}

func autoConvert_peer1_SubFooStruct_To_target1_SubFooStruct(in *peer1.SubFooStruct, out *SubFooStruct, s conversion.Scope) error {
	out.BoolSlice = *(*[]bool)(unsafe.Pointer(&in.BoolSlice))
	return nil
}

// Convert_peer1_SubFooStruct_To_target1_SubFooStruct is an autogenerated conversion function.
func Convert_peer1_SubFooStruct_To_target1_SubFooStruct(in *peer1.SubFooStruct, out *SubFooStruct, s conversion.Scope) error {
	return autoConvert_peer1_SubFooStruct_To_target1_SubFooStruct(in, out, s)
}
