os: Visual Studio 2017
platform: x64
clone_folder: c:\gopath\src\k8s.io\gengo

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8

init:
  - git config --global core.autocrlf input

install:
  # Install GNU Make for the tests.
  - ps: mkdir C:\GNUWin32
  - ps: Start-BitsTransfer -Source https://downloads.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip -Destination C:\GNUWin32
  - ps: Expand-Archive C:/GNUWin32/make-3.81-bin.zip -DestinationPath C:/GNUWin32
  # Install the specific Go version.
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - call "%VS150COMNTOOLS%\VsMSBuildCmd.bat"
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set PATH=c:\go\bin;c:\gopath\bin;c:\gnuwin32\bin;%PATH%
  - go version
  - go env
  - go get -t ./...

build: false
deploy: false

test_script:
  - ps: Get-ChildItem -Recurse -Include Makefile | foreach { echo "Building $(Split-Path -Path $_)..."; make -C (Split-Path -Path $_) test }
  - go test -v ./...
  - go run ./examples/import-boss/main.go -i k8s.io/gengo/... --verify-only
