//go:generate go run k8s.io/gengo/v2/examples/deepcopy-gen --output-file zz_generated.go --go-header-file=../../../boilerplate/boilerplate.go.txt k8s.io/gengo/v2/examples/deepcopy-gen/output_tests/...
package output_tests
