// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package postdeepcopy

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	reflect "reflect"
	unsafe "unsafe"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Alias_WithPostDeepCopy).DeepCopyInto(out.(*Alias_WithPostDeepCopy))
			return nil
		}, InType: reflect.TypeOf(new(Alias_WithPostDeepCopy))},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Struct_WithPostDeepCopy).DeepCopyInto(out.(*Struct_WithPostDeepCopy))
			return nil
		}, InType: reflect.TypeOf(new(Struct_WithPostDeepCopy))},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Struct_WithPostDeepCopyFields).DeepCopyInto(out.(*Struct_WithPostDeepCopyFields))
			return nil
		}, InType: reflect.TypeOf(new(Struct_WithPostDeepCopyFields))},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Struct_WithSkippedFields).DeepCopyInto(out.(*Struct_WithSkippedFields))
			return nil
		}, InType: reflect.TypeOf(new(Struct_WithSkippedFields))},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alias_WithPostDeepCopy) DeepCopyInto(out *Alias_WithPostDeepCopy) {
	{
		in := (*string)(unsafe.Pointer(in))
		out := (*string)(unsafe.Pointer(out))
		*out = *in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alias_WithPostDeepCopy.
func (in *Alias_WithPostDeepCopy) DeepCopy() *Alias_WithPostDeepCopy {
	if in == nil {
		return nil
	}
	out := new(Alias_WithPostDeepCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Struct_WithPostDeepCopy) DeepCopyInto(out *Struct_WithPostDeepCopy) {
	*out = *in
	in.postDeepCopy(out)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Struct_WithPostDeepCopy.
func (in *Struct_WithPostDeepCopy) DeepCopy() *Struct_WithPostDeepCopy {
	if in == nil {
		return nil
	}
	out := new(Struct_WithPostDeepCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Struct_WithPostDeepCopyFields) DeepCopyInto(out *Struct_WithPostDeepCopyFields) {
	*out = *in
	if in.APtr != nil {
		in, out := &in.APtr, &out.APtr
		if *in == nil {
			*out = nil
		} else {
			*out = new(Alias_WithPostDeepCopy)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ASlice != nil {
		in, out := &in.ASlice, &out.ASlice
		*out = make([]Alias_WithPostDeepCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AMap != nil {
		in, out := &in.AMap, &out.AMap
		*out = make(map[string]Alias_WithPostDeepCopy, len(*in))
		for key, val := range *in {
			newVal := new(Alias_WithPostDeepCopy)
			val.DeepCopyInto(newVal)
			(*out)[key] = *newVal
		}
	}
	in.S.DeepCopyInto(&out.S)
	if in.SPtr != nil {
		in, out := &in.SPtr, &out.SPtr
		if *in == nil {
			*out = nil
		} else {
			*out = new(Struct_WithPostDeepCopy)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.SSlice != nil {
		in, out := &in.SSlice, &out.SSlice
		*out = make([]Struct_WithPostDeepCopy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SMap != nil {
		in, out := &in.SMap, &out.SMap
		*out = make(map[string]Struct_WithPostDeepCopy, len(*in))
		for key, val := range *in {
			newVal := new(Struct_WithPostDeepCopy)
			val.DeepCopyInto(newVal)
			(*out)[key] = *newVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Struct_WithPostDeepCopyFields.
func (in *Struct_WithPostDeepCopyFields) DeepCopy() *Struct_WithPostDeepCopyFields {
	if in == nil {
		return nil
	}
	out := new(Struct_WithPostDeepCopyFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Struct_WithSkippedFields) DeepCopyInto(out *Struct_WithSkippedFields) {
	*out = *in
	if in.Ptr != nil {
		in, out := &in.Ptr, &out.Ptr
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	in.postDeepCopy(out)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Struct_WithSkippedFields.
func (in *Struct_WithSkippedFields) DeepCopy() *Struct_WithSkippedFields {
	if in == nil {
		return nil
	}
	out := new(Struct_WithSkippedFields)
	in.DeepCopyInto(out)
	return out
}
