//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kilroy. DO NOT EDIT.

package simple

// KilroyWasHere is an autogenerated method.
func (ExportedStruct) KilroyWasHere() {}

// KilroyWasHere is an autogenerated method.
func (UnderlyingStruct) KilroyWasHere() {}
